# Generated by Django 6.1 on 2026-08-07 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500, verbose_name='Project Name')),
                ('project_location', models.CharField(max_length=300, verbose_name='Location')),
                ('surveying_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Surveying Date')),
                ('description', models.TextField(default='...', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200, verbose_name='Method')),
                ('accuracy', models.CharField(max_length=200, verbose_name='Accuracy')),
                ('description', models.TextField(default='...', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='Receiver Name')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Manufacturer')),
                ('receiver_model', models.CharField(max_length=200, verbose_name='Receiver Model')),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_name', models.CharField(max_length=200, verbose_name='Satellite Name')),
                ('satellite_country', models.CharField(max_length=200, verbose_name='Satellite Country')),
            ],
        ),
    ]
