# Generated by Django 6.1 on 2026-08-07 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='gnss.receiver', verbose_name='Receiver'),
        ),
        migrations.AddField(
            model_name='mission',
            name='satellite_systems',
            field=models.ManyToManyField(blank=True, null=True, related_name='mission', to='gnss.satellitesystem', verbose_name='satellite system'),
        ),
        migrations.AddField(
            model_name='processingreport',
            name='mission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_report', to='gnss.mission', verbose_name='Mission'),
        ),
    ]
