# Generated by Django 6.1 on 2026-09-01 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnss', '0002_mission_receiver_mission_satellite_systems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='surveying_date',
        ),
        migrations.AddField(
            model_name='mission',
            name='surveying_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='mission',
            name='surveying_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='satellite_systems',
            field=models.ManyToManyField(blank=True, related_name='mission', to='gnss.satellitesystem', verbose_name='satellite system'),
        ),
    ]
