# Generated by Django 6.1 on 2026-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnss', '0003_remove_mission_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='gnss/mission_image/', verbose_name='Image'),
        ),
    ]
